//
// Created by 董启宏 on 2016/10/12.
//

#ifndef DATA_STRUCTURE_AND_ALGORITHM_BINARY_SEARCH_H
#define DATA_STRUCTURE_AND_ALGORITHM_BINARY_SEARCH_H

int BinarySearch(const int A[], int X, int N);

#endif //DATA_STRUCTURE_AND_ALGORITHM_BINARY_SEARCH_H
